config/routes.rb
Rails.application.routes.draw do
    #get 'donaciones/index'
   
  root 'dynamic_pages#home'
  get '/bienvenido', to: 'dynamic_pages#welcome'
  
  #get '/cocina', to: 'productos#index'
  resources :productos

  get  '/registrarusuario',  to: 'usuarios#new'
  post '/registrarusuario',  to: 'usuarios#create'
  post '/usuarios',  to: 'usuarios#index'
  get '/usuarios',  to: 'usuarios#index'
  post '/activarusuario',  to: 'usuarios#activate'
  post '/activarproducto', to: 'productos#activate'
  resources :usuarios
  resources :usuario_pass
  patch '/reestablecer/:id',  to: 'usuario_pass#update', as: 'update_usuario_pass'
  
  get  '/registrarpadre',  to: 'padres#new'
  post '/registrarpadre',  to: 'padres#create'
  resources :padres
  
  get '/historial', to: 'historials#index'
  post '/historial', to: 'historials#index'
  get  '/registrarhistorial', to: 'historials#new'
  post '/registrarhistorial', to: 'historials#create'
  delete '/historials/:id', to: 'historials#destroy', as: 'destroy_historial'
  patch 'historials/:id/edit', controller: 'historials', action: :update
  resources :historials
  resources :historial
  
  get '/terapeutas', to: 'terapeutas#index'
  post '/terapeutas', to: 'terapeutas#index'
  get '/terapeutas/:idUsuario', to: 'terapeutas#show'
  get '/terapeutas/:idUsuario/new',  to: 'terapeutas#new', as:'new_nino'
  post '/terapeutas/:idUsuario/new',  to: 'terapeutas#create', as:'assign_nino'
  post '/terapeutas/:idUsuario/:idNino', to: 'terapeutas#destroy', as:'destroy_nino'

  resources :sesiones, only:[:new, :create, :destroy]
  get 'login', to: 'sesiones#new', as:'login'
  #post 'login', to: 'sesiones#create', as:'login'
  get 'logout', to: 'sesiones#destroy', as:'logout'
  
  get  '/roles/new',  to: 'roles#new', as:'new_role'
  get  '/roles/:idRol',  to: 'roles#show'
  resources :roles
  get  '/roles_privilegio/:idRol/new',  to: 'roles_privilegios#new', as:'new_roles_privilegio'
  post '/roles_privilegio/:idRol/new',  to: 'roles_privilegios#create', as:'create_roles_privilegio'
  delete '/roles_privilegio/:idRol/:idPrivilegio/delete',  to: 'roles_privilegios#destroy', as:'delete_roles_privilegio'
  resources :roles_privilegio, only:[:new, :create, :destroy]
  
  resources :donadores
  post '/donadores/new', to: 'donadores#new'
  post '/donadores', to: 'donadores#index'
  post '/donadores/:id/edit', to: 'donadores#edit'
  patch '/donadores/:id', to: 'donadores#update'
  
  resources :pagos
    get '/mi_lista_alimentos', to: 'productos#mi_lista_alimentos'
    get '/pagos_hijo', to: 'pagos#pagos_hijo'
    get '/pagos_por_padre/:id', to: 'pagos#pagos_por_padre'
    #get '/pagos/new/:id', to: 'pagos#new'
    get '/pagos_por_padre/new/:id', to: 'pagos_padre#new'
    get '/pagos', to: 'pagos#index'
  
  resources :donaciones
  
  resources :listas
    get '/lista_asignada/:id', to: 'listas#lista_asignada'
    get '/listas/new/:id', to: 'listas#new'
    get 'asignar_productos/new', to: 'listas#asignar_productos'
    patch '/donadores/:id', to: 'donadores#update'
    
  resources :productos do
    member do
      get :desasignado
    end
  end
  post '/productos/new', to: 'productos#new'
  post '/productos', to: 'productos#index'
  post '/productos/:id/edit', to: 'productos#edit'
  #patch '/productos/:id', to: 'productos#update'
=begin
    get "/donadores" => index
    post "/donadores" => create
    delete "/donadores/:id" => delete
    get "/donadores/:id" => create
    get "/donadores/new" => new
    get "/donadores/:id/edit" => edit
    patch "/donadores/:id" => update
    put "/donadores/:id" => update
=end

  get  '/registrarnino',  to: 'nino#new'
  post  '/registrarnino',  to: 'nino#create'
  get '/ninos', to: 'nino#index'
  post '/ninos', to: 'nino#index'
  post '/activarnino',  to: 'nino#activate'
  resources :nino
  
  post '/proyectos', to: 'proyecto#create'
  get '/proyectos', to: 'proyecto#new'
  resources :proyecto
  get '/proyectos', to: 'proyecto#index'
  get '/proyecto/new', to: 'proyecto#new'
  get '/proyecto/edit', to: 'proyecto#edit'
  get '/proyecto', to: 'proyecto#index'
  
end

app/models/terapeuta.rb
class Terapeuta < ApplicationRecord
    belongs_to :usuario, foreign_key: "idUsuario"
    belongs_to :ninos, foreign_key: "idNino"
    validates :idUsuario, presence: true
    validates :idNino, presence: true
end

app/controllers/terapeutas_controller.rb
class TerapeutasController < ApplicationController
    def index
        if(params[:query] != nil)
          require 'will_paginate/array'
          @usuarios = Usuario.nombre_completo_terapeuta(params[:query]).paginate(page: params[:page])
        else
          @usuarios = Usuario.where(idRol: 2).order(:Nombre).paginate(page: params[:page])
        end
        @roles = Role.all
    end
    
    def show
        @usuario = Usuario.find(params[:idUsuario])
        @nino = Nino.where(idTerapeuta: params[:idUsuario]).paginate(page: params[:page])
    end
    
    def new
        @nino = Nino.where(idTerapeuta: nil, Activo: 1)  
    end
    
    def create
        @idUsuario = params[:idUsuario]
        @idNino = params[:nino]
        if(@idNino.count > 0)
            @idNino.each do |p| 
                if Nino.where(idNino: p).update(idTerapeuta: params[:idUsuario])
                    flash[:Exito] = "Niño(s) añadidos!"
                else
                    flash[:Error] = "Error al intentar guardar a los niños asignados. Intentelo más tarde."
                end
        end
        else
            flash[:Error] = "No se han seleccionado niños"
        end
        redirect_to "/terapeutas/#{@idUsuario}"
    end
    
    def destroy
        @idUsuario = params[:idUsuario]
        if Nino.where(idNino: params[:idNino]).update(idTerapeuta: nil)
            flash[:Exito] = "¡Niño desasignado correctamente!"
        else
            flash[:Error] = "Error al intentar desasignar al niño. Intentelo más tarde"
        end
        redirect_to "/terapeutas/#{@idUsuario}"
    end
end

app/helpers/terapeutas_helper.rb
module TerapeutasHelper
end

app/views/terapeutas/_form.html.erb
<% if(@nino.count > 0) %>
    <%= form_tag(assign_nino_path(params[:idUsuario]), method: "post", remote: true, html: { style: "display:inline;" }) do %>
    <table class="bordered highlight">
      <thead>
        <tr>
          <th></th>
          <th>idNiño</th>
          <th>Nombre completo</th>
          <th>Edad</th>
        </tr>
      </thead>
      <tbody>
        <div class="input-field col s12">
        <% @nino.each do |p| %>
          <tr>
            <td> 
              <input type="checkbox" name="nino[]" id="<%= p.idNino %>" value="<%= p.idNino %>"/>
              <label for="<%= p.idNino %>"></label></td>
              <td><%= p.idNino %></td>
              <td>
                <%= p.nombre+" "+p.ApellidoPaterno+" "+p.ApellidoMaterno %>
              </td>
              <td><%= p.Edad %></td>
            </tr>
          <% end %>
          </div>
        </tbody>
      </table>
      <br>
      <button class="btn waves-effect waves-light" type="submit" name="guardar" value="Listo">
        <a class="white-text">Guardar</a>
        <i class="material-icons right">save</i>
      </button>
      <%= link_to "Cancelar", "#", class: "modal-action modal-close waves-effect btn-flat", data: {dismiss: "modal"} %>
    <% end %>
  <% else %>
    <br>
    Ya han sido asignados todos los niños activos en el sistema.
  <% end %>

app/views/terapeutas/_new.html.erb
  <div class="modal-content">
    <h5>Asignar niños</h5>
    <div class="divider"></div>
    <%= render "form" %>
  </div>

app/views/terapeutas/index.html.erb
<% provide(:title, "Terapeutas") %>
<br>
<div class="row">
  <div class="col m8">
    <h4><%= t('my.therapists')%></h4>
  </div>
</div>

<div class="divider"></div>

<br>

<%= form_tag("/terapeutas", method: "post") do %>
  <div class="row">
    <div class="input-field col s4">
      <%= label_tag(:query, t('my.forms.search')) %>
      <%= text_field_tag(:query) %>
    </div>
    <div class="input-field col s4">
      <button class="btn waves-effect waves-light" type="submit" name="submit" value="enviar"><%= t('my.buttons.search')%>
          <i class="material-icons right">search</i>
      </button>
    </div>
  </div>
<% end %>

<br>
<br>

<div class="row">
  <div class="col m12">
    <%  if (@usuarios.count == 0) %>
      <div class="chip" id="error">
        <%= "No se encontraron terapeutas con ese nombre" %>
        <i class="close material-icons">close</i>
      </div> 
    <% else %>
    <%= will_paginate @usuarios, renderer: MaterializePagination::Rails %>
    <table class="highlight" id="usuarios">
        <thead>
          <tr>
              <th><%= t('my.full_name')%></th>
              <th><%= t('my.id_user')%></th>
              <th><%= t('my.email')%></th>
              <th><%= t('my.telephone')%></th>
              <th class="center-align"><%= t('my.child_assiged')%></th>
              <% if (tiene_permiso(current_user, 2)) %>
                <th><%= t('my.status')%></th>
              <% end %>
              <th><%= t('my.buttons.more')%></th>
          </tr>
        </thead>

        <tbody>
          <% @usuarios.each do |usuario| %>
          <% @asignado = Nino.where(idTerapeuta: usuario.idUsuario).count %>
          <tr>
            <td><%= link_to "#{usuario.Nombre} #{usuario.ApellidoPaterno} #{usuario.ApellidoMaterno}", usuario %></td>
            <!-- <td><%#= usuario.idUsuario %></td> -->
            <td><%= usuario.Correo %></td>
            <td><%= usuario.Telefono %></td>
            <td class="center-align"><%= @asignado %></td>
            <% if (tiene_permiso(current_user, 2)) %>
            <td>
              <div class="switch">
                <label>
                  No
                  <input id="Activo<%= usuario.idUsuario %>" name="Activo" type="checkbox" 
                  onclick="usuarioActivo(<%= usuario.idUsuario %>)" <%= if (usuario.Activo) 
                                                                              "checked" 
                                                                         end %>
                  >
                  <span class="lever"></span>
                  Si
                </label>
              </div>
            </td>
            <% end %>
            <td>
              <%= link_to '<i class="material-icons">trending_flat</i>'.html_safe, 
        		            usuario, class: 'btn-floating waves-effect waves-light'%> 
            </td>
          </tr>
          <% end %> 
        </tbody>
    </table>
    <%= will_paginate @usuarios, renderer: MaterializePagination::Rails %>
    <% end %>
  </div>
</div>

app/views/terapeutas/new.js.erb
$("#nino-modal").html("<%= escape_javascript(render 'new') %>")
$("#nino-modal").openModal()

app/views/terapeutas/show.html.erb
<br>
<% if (current_user.idRol == 2) %>
    <h4> Niños asignados a: <%= "#{@usuario.Nombre} #{@usuario.ApellidoPaterno} #{@usuario.ApellidoMaterno}" %> </h4>
<% else %>
	<h4>
		<%= link_to '<i class="material-icons">keyboard_backspace</i>'.html_safe, "/usuarios/#{@usuario.idUsuario}", class: 'btn-floating waves-effect waves-light'%> 
		 Niños asignados a: <%= "#{@usuario.Nombre} #{@usuario.ApellidoPaterno} #{@usuario.ApellidoMaterno}" %>
	</h4>
<% end %>
<div class="divider"></div>
<br>
<% if (@usuario.Activo == false) %>
    <br>
    <div class="chip">
        <%= "Necesita activar primero al terapeuta" %>
        <i class="close material-icons">close</i>
    </div> 
<% else %>
    <% if (tiene_permiso(current_user, 1)) %>
    	<a class="white-text" href="/terapeutas/<%= params[:idUsuario] %>/new" data-remote="true">
        <button class="btn waves-effect waves-light" >
            Asignar niños
            <i class="material-icons right">add</i>
        </button>
      </a>
    <% end %>
    <div class="row">
      <div class="col m12">
        <%  if (@nino.count == 0) %>
        <br>
             <div class="chip">
            <%= "No se encontraron niños asignados a este terapeuta" %>
            <i class="close material-icons">close</i>
          </div> 
        <% else %>
        <%= will_paginate @nino, renderer: MaterializePagination::Rails %>
    
    <table class="highlight" id="ninos">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>idNiño</th>
                <th>Fecha de nacimiento</th>
                <th>Edad</th>
                <% if (tiene_permiso(current_user, 3)) %>
                <th>Desasignar</th>
                <% end %>
                <th>Más</th>
            </tr>
        </thead>
        <tbody>
            <% @nino.each do |nino| %>
            <tr>
                <td><%= link_to nino.nombre+" "+nino.ApellidoPaterno+" "+nino.ApellidoMaterno, nino %></td>
                <td><%= nino.idNino %></td>
                <td><%= nino.FechaNacimiento %></td>
                <td><%= nino.Edad %></td>
                <% if (tiene_permiso(current_user, 3)) %>
                <td>
                <%= link_to '<i class="material-icons right">delete</i>'.html_safe, destroy_nino_path(params[:idUsuario],idNino: nino.idNino), method: :post,
                class: 'btn-floating waves-effect red', data: { confirm: "¿Está seguro que quiere desasignar a este niño?" }%>
                </td>
                <% end %>
                <td><%= link_to '<i class="material-icons">trending_flat</i>'.html_safe, 
    		            nino, class: 'btn-floating waves-effect waves-light'%></td>
            </tr>
            <% end %>
        </tbody>
    </table>
     <%= will_paginate @nino, renderer: MaterializePagination::Rails %>
        <% end %>
      </div>
    </div>
    
    <div id="nino-modal" class="modal"></div>
<% end %>