config/routes.rb
Rails.application.routes.draw do
    #get 'donaciones/index'
   
  root 'dynamic_pages#home'
  get '/bienvenido', to: 'dynamic_pages#welcome'
  
  #get '/cocina', to: 'productos#index'
  resources :productos

  get  '/registrarusuario',  to: 'usuarios#new'
  post '/registrarusuario',  to: 'usuarios#create'
  post '/usuarios',  to: 'usuarios#index'
  get '/usuarios',  to: 'usuarios#index'
  post '/activarusuario',  to: 'usuarios#activate'
  post '/activarproducto', to: 'productos#activate'
  resources :usuarios
  resources :usuario_pass
  patch '/reestablecer/:id',  to: 'usuario_pass#update', as: 'update_usuario_pass'
  
  get  '/registrarpadre',  to: 'padres#new'
  post '/registrarpadre',  to: 'padres#create'
  resources :padres
  
  get '/historial', to: 'historials#index'
  post '/historial', to: 'historials#index'
  get  '/registrarhistorial', to: 'historials#new'
  post '/registrarhistorial', to: 'historials#create'
  delete '/historials/:id', to: 'historials#destroy', as: 'destroy_historial'
  patch 'historials/:id/edit', controller: 'historials', action: :update
  resources :historials
  resources :historial
  
  get '/terapeutas', to: 'terapeutas#index'
  post '/terapeutas', to: 'terapeutas#index'
  get '/terapeutas/:idUsuario', to: 'terapeutas#show'
  get '/terapeutas/:idUsuario/new',  to: 'terapeutas#new', as:'new_nino'
  post '/terapeutas/:idUsuario/new',  to: 'terapeutas#create', as:'assign_nino'
  post '/terapeutas/:idUsuario/:idNino', to: 'terapeutas#destroy', as:'destroy_nino'

  resources :sesiones, only:[:new, :create, :destroy]
  get 'login', to: 'sesiones#new', as:'login'
  #post 'login', to: 'sesiones#create', as:'login'
  get 'logout', to: 'sesiones#destroy', as:'logout'
  
  get  '/roles/new',  to: 'roles#new', as:'new_role'
  get  '/roles/:idRol',  to: 'roles#show'
  resources :roles
  get  '/roles_privilegio/:idRol/new',  to: 'roles_privilegios#new', as:'new_roles_privilegio'
  post '/roles_privilegio/:idRol/new',  to: 'roles_privilegios#create', as:'create_roles_privilegio'
  delete '/roles_privilegio/:idRol/:idPrivilegio/delete',  to: 'roles_privilegios#destroy', as:'delete_roles_privilegio'
  resources :roles_privilegio, only:[:new, :create, :destroy]
  
  resources :donadores
  post '/donadores/new', to: 'donadores#new'
  post '/donadores', to: 'donadores#index'
  post '/donadores/:id/edit', to: 'donadores#edit'
  patch '/donadores/:id', to: 'donadores#update'
  
  resources :pagos
    get '/mi_lista_alimentos', to: 'productos#mi_lista_alimentos'
    get '/pagos_hijo', to: 'pagos#pagos_hijo'
    get '/pagos_por_padre/:id', to: 'pagos#pagos_por_padre'
    #get '/pagos/new/:id', to: 'pagos#new'
    get '/pagos_por_padre/new/:id', to: 'pagos_padre#new'
    get '/pagos', to: 'pagos#index'
  
  resources :donaciones
  
  resources :listas
    get '/lista_asignada/:id', to: 'listas#lista_asignada'
    get '/listas/new/:id', to: 'listas#new'
    get 'asignar_productos/new', to: 'listas#asignar_productos'
    patch '/donadores/:id', to: 'donadores#update'
    
  resources :productos do
    member do
      get :desasignado
    end
  end
  post '/productos/new', to: 'productos#new'
  post '/productos', to: 'productos#index'
  post '/productos/:id/edit', to: 'productos#edit'
  #patch '/productos/:id', to: 'productos#update'
=begin
    get "/donadores" => index
    post "/donadores" => create
    delete "/donadores/:id" => delete
    get "/donadores/:id" => create
    get "/donadores/new" => new
    get "/donadores/:id/edit" => edit
    patch "/donadores/:id" => update
    put "/donadores/:id" => update
=end

  get  '/registrarnino',  to: 'nino#new'
  post  '/registrarnino',  to: 'nino#create'
  get '/ninos', to: 'nino#index'
  post '/ninos', to: 'nino#index'
  post '/activarnino',  to: 'nino#activate'
  resources :nino
  
  post '/proyectos', to: 'proyecto#create'
  get '/proyectos', to: 'proyecto#new'
  resources :proyecto
  get '/proyectos', to: 'proyecto#index'
  get '/proyecto/new', to: 'proyecto#new'
  get '/proyecto/edit', to: 'proyecto#edit'
  get '/proyecto', to: 'proyecto#index'
  
end

app/models/nino.rb
class Nino < ApplicationRecord
    has_one :padre, foreign_key: "idNino",
                   dependent:   :destroy
    #has_one :terapeuta, foreign_key: "idNino",
    #              dependent:   :destroy
    has_one :usuario, foreign_key: "idUsuario", as: "terapeuta",
                  dependent:   :destroy
    #has_one :usuario, :through => :padre
    has_many :historials, foreign_key: "idNino",
                   dependent:   :destroy
                   
    validates :nombre, presence: true, length: { maximum: 45 }
    validates :ApellidoPaterno, presence: true, length: { maximum: 45 }
    validates :ApellidoMaterno, presence: true, length: { maximum: 45 }
    validates :FechaNacimiento, presence: true
    validates :Edad, presence: true, numericality: true 
    validates :PorcentajeBeca, presence: true
    #validates :Sexo, presence: true
    #validates :Activo, presence: true
    validates :Fechaingreso, presence: true
    validates :PorcentajeBeca, presence: true
    validates :Direccion, presence: true
    
    
    def Nino.nombre_completo(query)
        if Rails.env.development?
            db = "skoolapp_development_db" 
        elsif Rails.env.test?
            db = "skoolapp_test_db"
        elsif Rails.env.production?
            db = "skoolapp_production_db"
        end
        find_by_sql("SELECT *, CONCAT(skoolapp_development_db.ninos.nombre, \" \", skoolapp_development_db.ninos.ApellidoPaterno,
        \" \", skoolapp_development_db.ninos.ApellidoMaterno) as NombreCompleto 
        FROM skoolapp_development_db.ninos
        HAVING (NombreCompleto LIKE \"%#{query}%\")
        ORDER BY NombreCompleto asc")
    end
end

app/controllers/nino_controller.rb
class NinoController < ApplicationController
    before_action :validate_user
    def show
        @nino = Nino.find(params[:id])
        if (@nino.idTerapeuta != nil)
            @terapeuta = Usuario.find(@nino.idTerapeuta)
        end
    end
    
    def new
        @nino = Nino.new
    end
    
    def create
        @nino = Nino.new(nino_params)
        if @nino.save
            flash[:success] = "registrado exitosamente!"
            redirect_to @nino
        else
            render 'new'
        end
    end
    
    def index
        if(params[:query] != nil)
            require 'will_paginate/array'
            @nino = Nino.nombre_completo(params[:query]).paginate(page: params[:page])
        else
            @nino = Nino.all.order(:nombre).paginate(page: params[:page])
        end
    end
    
    def activate
    @nino = Nino.find(params[:idNino])
    if @nino.update_attribute(:Activo, params[:data])
    else
      
    end
     #redirect_to '/usuarios'
    end
    
    def edit
        @nino = Nino.find(params[:id])
    end
    
    def update
        @nino = Nino.find(params[:id])
        if @nino.update_attributes(nino_params)
            redirect_to @nino
        else
            render 'edit'
        end
    end
    
    
    private

    def nino_params
      params.require(:nino).permit(:nombre, :ApellidoPaterno, :ApellidoMaterno, :FechaNacimiento, :Fechaingreso, :Edad, :Sexo, :Activo,:PorcentajeBeca, :Direccion)
    end
    
end

app/helpers/nino_helper.rb
module NinoHelper
end

app/views/nino/edit.html.erb
<br>
<%= form_for(@nino) do |f| %>
<h4> <%= link_to '<i class="material-icons left">keyboard_backspace</i>'.html_safe, :back, class: 'btn-floating waves-effect waves-light'%> <%= t('my.titles.childs.edit')%> <%= @nino.nombre+" "+@nino.ApellidoPaterno+" "+@nino.ApellidoMaterno %></h4>
<div class="divider"></div>
<br>

<div class="row">
  <div class="col m6 offset-m3">
    <%= render 'shared/error_messages', object: f.object %>
    
     <div class="input-field">
        <%= f.label t('my.titles.tables.childs.name'), class: 'active' %>
        <%= f.text_field :nombre, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.last_name'), class: 'active' %>
        <%= f.text_field :ApellidoPaterno, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.mother_last_name'), class: 'active' %>
        <%= f.text_field :ApellidoMaterno, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.birthdate'), class: 'active' %>
        <%= f.date_field :FechaNacimiento, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.date_admission'), class: 'active' %>
        <%= f.date_field :Fechaingreso, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.age'), class: 'active' %>
        <%= f.number_field :Edad, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <select name="nino[Sexo]" id="nino_Sexo" required>
          <option value="<%= @nino.Sexo %>" selected><%= t('my.titles.tables.childs.sex')%> <%= @nino.Sexo %></option>
          <option value="Masculino">Masculino</option>
          <option value="Femenino">Femenino</option>
        </select>
      </div>
      
      <div class="input-field">
        <select name="nino[Activo]" id="nino_Activo" required>
          <option value="<%= @nino.Activo %>" selected>Activo: <%= if (@nino.Activo) 
                                                                        "(Si)" 
                                                                      else
                                                                        "(No)"
                                                                      end %> </option>
            <option value="1">Activar</option>
            <option value="0">Desactivar</option>
        </select>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.percentage_b'), class: 'active'%>
        <%= f.number_field :PorcentajeBeca, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.address'), class: 'active' %>
        <%= f.text_field :Direccion, class: 'validate', required: 'true' %>
      </div>
      
      <%= f.submit t('my.buttons.save'), class: "btn waves-effect waves-light" %>
    <% end %>
        
</div>
</div>

app/views/nino/index.html.erb
<br>
<h4><%= t('my.titles.childs.index')%></h4> 
<div class="divider"></div>
<br>

<%= form_tag("/ninos", method: "post") do %>
  <div class="row">
    <div class="input-field col s4">
      <%= label_tag(:query, t('my.forms.search')) %>
      <%= text_field_tag(:query) %>
    </div>
  <div class="input-field col s4">
      <button class="btn waves-effect waves-light" type="submit" name="submit" value="enviar"><%= t('my.buttons.search')%>
          <i class="material-icons right">search</i>
      </button>
    </div>
  </div>
<% end %>


<div class="row">
  <div class="col m12">
    <%  if (@nino.count == 0) %>
         <div class="chip">
        <%= t('my.not_found.search_child') %>
        <i class="close material-icons">close</i>
      </div> 
    <% else %>
    <%= will_paginate @nino, renderer: MaterializePagination::Rails %>

<table class="highlight" id="ninos">
    <thead>
        <tr>
            <th><%= t('my.titles.tables.childs.name')%></th>
            <th><%= t('my.titles.tables.childs.id')%></th>
            <th><%= t('my.titles.tables.childs.birthdate')%></th>
            <th><%= t('my.titles.tables.childs.date_admission')%></th>
            <th><%= t('my.titles.tables.childs.age')%></th>
            <th><%= t('my.titles.tables.childs.status')%></th>
            <th><%= t('my.buttons.more')%></th>
        </tr>
    </thead>
    <tbody>
        <% @nino.each do |nino| %>
        <tr>
            <td><%= link_to nino.nombre+" "+nino.ApellidoPaterno+" "+nino.ApellidoMaterno, nino %></td>
            <td><%= nino.idNino %></td>
            <td><%= I18n.l nino.FechaNacimiento, format: :long %></td>
            <td><%= I18n.l nino.Fechaingreso, format: :long %></td>
            <td><%= nino.Edad %></td>
            <td>
                <div class="switch">
        <label>
          No
          <input id="Activo<%= nino.idNino %>" name="Activo" type="checkbox" 
          onclick="ninoActivo(<%= nino.idNino %>)" <%= if (nino.Activo) 
                                                                      "checked" 
                                                                 end %>
          >
          <span class="lever"></span>
          Si
        </label>
                
            </td>
            <td><%= link_to '<i class="material-icons">trending_flat</i>'.html_safe, 
		            nino, class: 'btn-floating waves-effect waves-light'%></td>
        </tr>
        <% end %>
    </tbody>
</table>
 <%= will_paginate @nino, renderer: MaterializePagination::Rails %>
    <% end %>
  </div>
</div>

app/views/nino/new.html.erb
<br>
<h4> <%= link_to '<i class="material-icons left">keyboard_backspace</i>'.html_safe, :back, class: 'btn-floating waves-effect waves-light'%> <%= t('my.titles.childs.new')%></h4>
<div class="divider"></div>
<br>

<%= form_for(@nino, url: registrarnino_path) do |f| %>
<%= render 'shared/error_messages', object: @nino %>
<div class="row">
      <div class="col m6 offset-m3">
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.name'), class: 'active'  %>
        <%= f.text_field :nombre, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.last_name'), class: 'active'  %>
        <%= f.text_field :ApellidoPaterno, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.mother_last_name'), class: 'active'  %>
        <%= f.text_field :ApellidoMaterno, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.birthdate'), class: 'active' %>
        <%= f.date_field :FechaNacimiento, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.date_admission'), class: 'active' %>
        <%= f.date_field :Fechaingreso, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.age'), class: 'active'  %>
        <%= f.number_field :Edad, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <select name="nino[Sexo]" id="nino_Sexo" required>
          <option value="<%= @nino.Sexo %>" selected><%= t('my.titles.tables.childs.sex')%>: <%= @nino.Sexo %></option>
          <option value="Masculino">Masculino</option>
          <option value="Femenino">Femenino</option>
        </select>
      </div>
      
      <div class="input-field">
        <select name="nino[Activo]" id="nino_Activo" required>
          <option value="<%= @nino.Activo %>" selected>Activo: <%= if (@nino.Activo) 
                                                                        "(Si)" 
                                                                      else
                                                                        "(No)"
                                                                      end %> </option>
            <option value="1">Activar</option>
            <option value="0">Desactivar</option>
        </select>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.percentage_b'), class: 'active' %>
        <%= f.number_field :PorcentajeBeca, class: 'validate', required: 'true' %>
      </div>
      
      <div class="input-field">
        <%= f.label t('my.titles.tables.childs.address'), class: 'active' %>
        <%= f.text_field :Direccion, class: 'validate', required: 'true' %>
      </div>
      <%= f.submit t('my.buttons.save'), class: "btn waves-effect waves-light" %>
    <% end %>
    </div>
  </div>
</div>

app/views/nino/show.html.erb
<br>
<% if (current_user.idRol == 2) %>
	<% if (tiene_permiso(current_user, 16)) %>
		<h4> <%= link_to '<i class="material-icons left">keyboard_backspace</i>'.html_safe, "/terapeutas/#{current_user.idUsuario}", class: 'btn-floating waves-effect waves-light'%> Perfil de: <%= @nino.nombre+" "+@nino.ApellidoPaterno+" "+@nino.ApellidoMaterno %></h4>
	<% end %>
<% else %>
	<% if (tiene_permiso(current_user, 11)) %>
		<h4> <%= link_to '<i class="material-icons left">keyboard_backspace</i>'.html_safe, ninos_path, class: 'btn-floating waves-effect waves-light'%> Perfil de: <%= @nino.nombre+" "+@nino.ApellidoPaterno+" "+@nino.ApellidoMaterno %></h4>
	<% end %>
<% end %>
<div class="divider"></div>
<br>

		<% if (tiene_permiso(current_user, 2)) %>
			<a href="<%= edit_nino_path(@nino)%>" class="btn waves-effect waves-light" type="button"><%= t('my.buttons.edit')%><i class="material-icons right">mode_edit</i></a>
				<%#= link_to "Editar  " '<i class="material-icons right">mode_edit</i>'.html_safe, 
				edit_nino_path(@nino), class: 'btn waves-effect waves-light'%>
		<% end %>
		<% if (tiene_permiso(current_user, 15)) %>
			<a href="<%= historial_path(@nino)%>" class="btn waves-effect waves-light" type="button"><%= t('my.buttons.medical_history')%><i class="material-icons right">note_add</i></a>
				<%#= link_to "Historial Médico  " '<i class="material-icons right">note_add</i>'.html_safe, 
      		historial_path(@nino), class: 'btn waves-effect waves-light'%>
      	<% end %>
    <% if (current_user.idRol != 2) %>				
    <% if (!!@nino.padre) %>
    	<% if(@nino.padre.usuario == current_user) %>
    		<a href="<%= usuario_path(@nino.padre.usuario)%>" class="btn waves-effect waves-light" type="button"><%= t('my.buttons.my_profile')%><i class="material-icons right">perm_identity</i></a>
				<%#= link_to "Mi perfil" '<i class="material-icons right">perm_identity</i>'.html_safe, 
           usuario_path(@nino.padre.usuario), class: 'btn waves-effect waves-light'%>
			<% else %>
			<a href="<%= usuario_path(@nino.padre.usuario)%>" class="btn waves-effect waves-light" type="button"><%= t('my.buttons.parent_profile')%><i class="material-icons right">perm_identity</i></a>
				<%#= link_to "Perfil de padre" '<i class="material-icons right">perm_identity</i>'.html_safe, 
           usuario_path(@nino.padre.usuario), class: 'btn waves-effect waves-light'%>
			<% end %>
    <% else %>
     	<% if (tiene_permiso(current_user, 1)) %>
     		<a href="<%= registrarpadre_path(@nino)%>" class="btn waves-effect waves-light" type="button"><%= t('my.buttons.register_parent')%><i class="material-icons right">perm_identity</i></a>
        <%#= link_to "Registrar Padre" '<i class="material-icons right">perm_identity</i>'.html_safe, 
           registrarpadre_path(@nino), class: 'btn waves-effect waves-light'%>
      <% end %>
    <% end %>
    <% if (@nino.idTerapeuta != nil) %>
    	<a href="/usuarios/<%= @terapeuta.idUsuario%>" class="btn waves-effect waves-light" type="button"><%= t('my.buttons.teraphist_profile')%><i class="material-icons right">perm_identity</i></a>
    <%#= link_to "Perfil de terapeuta" '<i class="material-icons right">perm_identity</i>'.html_safe, 
           "/usuarios/#{@terapeuta.idUsuario}", class: 'btn waves-effect waves-light'%>
			<% end %>
    <% end %>

<div class="row">
  <div class="col m6 offset-m3">
  <br>
  		<% if (@nino.idTerapeuta != nil) %>
  		<label class="active" for="Terapeuta"><strong><%= t('my.titles.tables.childs.therapist_assigned')%></strong></label>
		<p id="Terapeuta"><%= @terapeuta.Nombre+" "+@terapeuta.ApellidoPaterno+" "+@terapeuta.ApellidoMaterno %></p>
		<div class="divider"></div>
		<br>
		<% else %>
		<label class="active" for="Terapeuta"><strong><%= t('my.titles.tables.childs.therapist_assigned')%></strong></label>
		<p id="Terapeuta">Ninguno</p>
		<div class="divider"></div>
		<br>
		<% end %>
		<label class="active" for="NacimientoNino"><strong><%= t('my.titles.tables.childs.birthdate')%></strong></label>
		<p id="NacimientoNino"><%= I18n.l @nino.FechaNacimiento, format: :long %></p>
		<div class="divider"></div>
		<br>
		
		<label class="active" for="IngresoNino"><strong><%= t('my.titles.tables.childs.date_admission')%></strong></label>
		<p id="IngresoNino"><%= I18n.l @nino.Fechaingreso, format: :long %></p>
		<div class="divider"></div>
		<br>

		<label class="active" for="Edad"><strong><%= t('my.titles.tables.childs.age')%></strong></label>
		<p id="Edad"><%= @nino.Edad %></p>
		<div class="divider"></div>
		<br>

		<label class="active" for="Sexo"><strong><%= t('my.titles.tables.childs.sex')%></strong></label>
		<p id="Sexo"><%= @nino.Sexo %></p>
		<div class="divider"></div>
		<br>

		<label class="active" for="Activo"><strong><%= t('my.titles.tables.childs.status')%></strong></label>
		<p id="Activo">
		<%= 
		if(@nino.Activo)
			"Activo"
		else 
		  "Inactivo"
		end
	  %>
	  	<div class="divider"></div>
  	</p>
  	
  		<label class="active" for="PorcentajeBeca"><strong><%= t('my.titles.tables.childs.percentaje')%></strong></label>
		<p id="PorcentajeBeca"><%= @nino.PorcentajeBeca %></p>
		<div class="divider"></div>
		<br>
		
		<label class="active" for="Direccion"><strong><%= t('my.titles.tables.childs.address')%></strong></label>
		<p id="Direccion"><%= @nino.Direccion %></p>
		<div class="divider"></div>
		<br>
  	
  	<br>
  </div>
</div>