config/routes.rb
Rails.application.routes.draw do
    #get 'donaciones/index'
   
  root 'dynamic_pages#home'
  get '/bienvenido', to: 'dynamic_pages#welcome'
  
  #get '/cocina', to: 'productos#index'
  resources :productos

  get  '/registrarusuario',  to: 'usuarios#new'
  post '/registrarusuario',  to: 'usuarios#create'
  post '/usuarios',  to: 'usuarios#index'
  get '/usuarios',  to: 'usuarios#index'
  post '/activarusuario',  to: 'usuarios#activate'
  post '/activarproducto', to: 'productos#activate'
  resources :usuarios
  resources :usuario_pass
  patch '/reestablecer/:id',  to: 'usuario_pass#update', as: 'update_usuario_pass'
  
  get  '/registrarpadre',  to: 'padres#new'
  post '/registrarpadre',  to: 'padres#create'
  resources :padres
  
  get '/historial', to: 'historials#index'
  post '/historial', to: 'historials#index'
  get  '/registrarhistorial', to: 'historials#new'
  post '/registrarhistorial', to: 'historials#create'
  delete '/historials/:id', to: 'historials#destroy', as: 'destroy_historial'
  patch 'historials/:id/edit', controller: 'historials', action: :update
  resources :historials
  resources :historial
  
  get '/terapeutas', to: 'terapeutas#index'
  post '/terapeutas', to: 'terapeutas#index'
  get '/terapeutas/:idUsuario', to: 'terapeutas#show'
  get '/terapeutas/:idUsuario/new',  to: 'terapeutas#new', as:'new_nino'
  post '/terapeutas/:idUsuario/new',  to: 'terapeutas#create', as:'assign_nino'
  post '/terapeutas/:idUsuario/:idNino', to: 'terapeutas#destroy', as:'destroy_nino'

  resources :sesiones, only:[:new, :create, :destroy]
  get 'login', to: 'sesiones#new', as:'login'
  #post 'login', to: 'sesiones#create', as:'login'
  get 'logout', to: 'sesiones#destroy', as:'logout'
  
  get  '/roles/new',  to: 'roles#new', as:'new_role'
  get  '/roles/:idRol',  to: 'roles#show'
  resources :roles
  get  '/roles_privilegio/:idRol/new',  to: 'roles_privilegios#new', as:'new_roles_privilegio'
  post '/roles_privilegio/:idRol/new',  to: 'roles_privilegios#create', as:'create_roles_privilegio'
  delete '/roles_privilegio/:idRol/:idPrivilegio/delete',  to: 'roles_privilegios#destroy', as:'delete_roles_privilegio'
  resources :roles_privilegio, only:[:new, :create, :destroy]
  
  resources :donadores
  post '/donadores/new', to: 'donadores#new'
  post '/donadores', to: 'donadores#index'
  post '/donadores/:id/edit', to: 'donadores#edit'
  patch '/donadores/:id', to: 'donadores#update'
  
  resources :pagos
    get '/mi_lista_alimentos', to: 'productos#mi_lista_alimentos'
    get '/pagos_hijo', to: 'pagos#pagos_hijo'
    get '/pagos_por_padre/:id', to: 'pagos#pagos_por_padre'
    #get '/pagos/new/:id', to: 'pagos#new'
    get '/pagos_por_padre/new/:id', to: 'pagos_padre#new'
    get '/pagos', to: 'pagos#index'
  
  resources :donaciones
  
  resources :listas
    get '/lista_asignada/:id', to: 'listas#lista_asignada'
    get '/listas/new/:id', to: 'listas#new'
    get 'asignar_productos/new', to: 'listas#asignar_productos'
    patch '/donadores/:id', to: 'donadores#update'
    
  resources :productos do
    member do
      get :desasignado
    end
  end
  post '/productos/new', to: 'productos#new'
  post '/productos', to: 'productos#index'
  post '/productos/:id/edit', to: 'productos#edit'
  #patch '/productos/:id', to: 'productos#update'
=begin
    get "/donadores" => index
    post "/donadores" => create
    delete "/donadores/:id" => delete
    get "/donadores/:id" => create
    get "/donadores/new" => new
    get "/donadores/:id/edit" => edit
    patch "/donadores/:id" => update
    put "/donadores/:id" => update
=end

  get  '/registrarnino',  to: 'nino#new'
  post  '/registrarnino',  to: 'nino#create'
  get '/ninos', to: 'nino#index'
  post '/ninos', to: 'nino#index'
  post '/activarnino',  to: 'nino#activate'
  resources :nino
  
  post '/proyectos', to: 'proyecto#create'
  get '/proyectos', to: 'proyecto#new'
  resources :proyecto
  get '/proyectos', to: 'proyecto#index'
  get '/proyecto/new', to: 'proyecto#new'
  get '/proyecto/edit', to: 'proyecto#edit'
  get '/proyecto', to: 'proyecto#index'
  
end

app/models/roles_privilegio.rb
class RolesPrivilegio < ApplicationRecord
    belongs_to :role, foreign_key: "idRol"
    belongs_to :privilegio, foreign_key: "idPrivilegio"
    validates :idPrivilegio, presence: true
    validates :idRol, presence: true
end

app/controllers/roles_privilegios_controller.rb
class RolesPrivilegiosController < ApplicationController
  before_action :validate_user
  
  before_action do
    tiene_permiso_controller(current_user, 6)
  end
  
  before_action only: [:new, :create] do
    tiene_permiso_controller(current_user, 2)
  end
  
  before_action only: [:destroy] do
    tiene_permiso_controller(current_user, 3)
  end
  
  # GET /roles/new
  def new
    @role = Role.find(params[:idRol])
    @privilegios = Privilegio.where.not(idPrivilegio: RolesPrivilegio.where(idRol: @role.idRol).map(&:idPrivilegio)) 
  end
  
  # POST /roles
  # POST /roles.json
  def create
    @role = Role.find(params[:idRol])
    @idPrivilegios = params[:privilegio]
    if(@idPrivilegios.count > 0)
      @idPrivilegios.each do |p| 
        @rolePrivilegio = RolesPrivilegio.new(:idRol => @role.idRol, :idPrivilegio => p)
        if @rolePrivilegio.save
          flash[:Exito] = "Privilegio(s) añadidos!"
        else
          flash[:Error] = "Error al intentar guardar los privilegios. Intentelo más tarde."
        end
      end
    else
      flash[:Error] = "No se han seleccionado privilegios"
    end
    redirect_to @role
  end


  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    #@rolePrivilegio.destroy
    @idRol = params[:idRol]
    @idPrivilegio = params[:idPrivilegio]
    RolesPrivilegio.delete_all(idRol: @idRol, idPrivilegio: @idPrivilegio)
    flash[:Exito] = "Privilegio eliminado"
    redirect_to "/roles/#{@idRol}"
  end
end

app/helpers/roles_privilegios_helper.rb
module RolesPrivilegiosHelper
end

app/views/roles_privilegios/_form.html.erb
<% if(@privilegios.count > 0) %>
<%= form_tag(create_roles_privilegio_path(@role), method: "post", remote: true, html: { style: "display:inline;" }) do %>
  <table class="bordered highlight">
    <thead>
      <tr>
        <th></th>
        <th><%= t('my.privileges_name')%></th>
        <th><%= t('my.description')%></th>
      </tr>
    </thead>
    <tbody>
      <div class="input-field col s12">
      <% @privilegios.each do |p| %>
        <tr>
          <td> 
            <input type="checkbox" name="privilegio[]" id="<%= p.idPrivilegio %>" value="<%= p.idPrivilegio %>"/>
            <label for="<%= p.idPrivilegio %>"></label></td>
            <td>
              <%= p.Nombre %>
            </td>
            <td>
              <%= p.Descripcion %>
            </td>
          </tr>
        <% end %>
        </div>
      </tbody>
    </table>
    <br>
    <button class="btn waves-effect waves-light" type="submit" name="guardar" value="Listo">
      <a class="white-text"><%= t('my.buttons.save')%></a>
      <i class="material-icons right">save</i>
    </button>
    <%= link_to t('my.buttons.cancel'), "#", class: "modal-action modal-close waves-effect btn-flat", data: {dismiss: "modal"} %>
  <% end %>
<% else %>
  <br>
  <%= t('my.ya_assinged')%>
<% end %>

app/views/roles_privilegios/_new.html.erb
<div class="modal-content">
  <h5><%= t('my.add_privileges')%></h5>
  <div class="divider"></div>
    
<%= render "form" %>

</div>

app/views/roles_privilegios/new.js.erb
$("#privilegios-modal").html("<%= escape_javascript(render 'new') %>")
$("#privilegios-modal").openModal()