config/routes.rb
Rails.application.routes.draw do
    #get 'donaciones/index'
   
  root 'dynamic_pages#home'
  get '/bienvenido', to: 'dynamic_pages#welcome'
  
  #get '/cocina', to: 'productos#index'
  resources :productos

  get  '/registrarusuario',  to: 'usuarios#new'
  post '/registrarusuario',  to: 'usuarios#create'
  post '/usuarios',  to: 'usuarios#index'
  get '/usuarios',  to: 'usuarios#index'
  post '/activarusuario',  to: 'usuarios#activate'
  post '/activarproducto', to: 'productos#activate'
  resources :usuarios
  resources :usuario_pass
  patch '/reestablecer/:id',  to: 'usuario_pass#update', as: 'update_usuario_pass'
  
  get  '/registrarpadre',  to: 'padres#new'
  post '/registrarpadre',  to: 'padres#create'
  resources :padres
  
  get '/historial', to: 'historials#index'
  post '/historial', to: 'historials#index'
  get  '/registrarhistorial', to: 'historials#new'
  post '/registrarhistorial', to: 'historials#create'
  delete '/historials/:id', to: 'historials#destroy', as: 'destroy_historial'
  patch 'historials/:id/edit', controller: 'historials', action: :update
  resources :historials
  resources :historial
  
  get '/terapeutas', to: 'terapeutas#index'
  post '/terapeutas', to: 'terapeutas#index'
  get '/terapeutas/:idUsuario', to: 'terapeutas#show'
  get '/terapeutas/:idUsuario/new',  to: 'terapeutas#new', as:'new_nino'
  post '/terapeutas/:idUsuario/new',  to: 'terapeutas#create', as:'assign_nino'
  post '/terapeutas/:idUsuario/:idNino', to: 'terapeutas#destroy', as:'destroy_nino'

  resources :sesiones, only:[:new, :create, :destroy]
  get 'login', to: 'sesiones#new', as:'login'
  #post 'login', to: 'sesiones#create', as:'login'
  get 'logout', to: 'sesiones#destroy', as:'logout'
  
  get  '/roles/new',  to: 'roles#new', as:'new_role'
  get  '/roles/:idRol',  to: 'roles#show'
  resources :roles
  get  '/roles_privilegio/:idRol/new',  to: 'roles_privilegios#new', as:'new_roles_privilegio'
  post '/roles_privilegio/:idRol/new',  to: 'roles_privilegios#create', as:'create_roles_privilegio'
  delete '/roles_privilegio/:idRol/:idPrivilegio/delete',  to: 'roles_privilegios#destroy', as:'delete_roles_privilegio'
  resources :roles_privilegio, only:[:new, :create, :destroy]
  
  resources :donadores
  post '/donadores/new', to: 'donadores#new'
  post '/donadores', to: 'donadores#index'
  post '/donadores/:id/edit', to: 'donadores#edit'
  patch '/donadores/:id', to: 'donadores#update'
  
  resources :pagos
    get '/mi_lista_alimentos', to: 'productos#mi_lista_alimentos'
    get '/pagos_hijo', to: 'pagos#pagos_hijo'
    get '/pagos_por_padre/:id', to: 'pagos#pagos_por_padre'
    #get '/pagos/new/:id', to: 'pagos#new'
    get '/pagos_por_padre/new/:id', to: 'pagos_padre#new'
    get '/pagos', to: 'pagos#index'
  
  resources :donaciones
  
  resources :listas
    get '/lista_asignada/:id', to: 'listas#lista_asignada'
    get '/listas/new/:id', to: 'listas#new'
    get 'asignar_productos/new', to: 'listas#asignar_productos'
    patch '/donadores/:id', to: 'donadores#update'
    
  resources :productos do
    member do
      get :desasignado
    end
  end
  post '/productos/new', to: 'productos#new'
  post '/productos', to: 'productos#index'
  post '/productos/:id/edit', to: 'productos#edit'
  #patch '/productos/:id', to: 'productos#update'
=begin
    get "/donadores" => index
    post "/donadores" => create
    delete "/donadores/:id" => delete
    get "/donadores/:id" => create
    get "/donadores/new" => new
    get "/donadores/:id/edit" => edit
    patch "/donadores/:id" => update
    put "/donadores/:id" => update
=end

  get  '/registrarnino',  to: 'nino#new'
  post  '/registrarnino',  to: 'nino#create'
  get '/ninos', to: 'nino#index'
  post '/ninos', to: 'nino#index'
  post '/activarnino',  to: 'nino#activate'
  resources :nino
  
  post '/proyectos', to: 'proyecto#create'
  get '/proyectos', to: 'proyecto#new'
  resources :proyecto
  get '/proyectos', to: 'proyecto#index'
  get '/proyecto/new', to: 'proyecto#new'
  get '/proyecto/edit', to: 'proyecto#edit'
  get '/proyecto', to: 'proyecto#index'
  
end

app/models/producto.rb
class Producto < ApplicationRecord
    has_many :listas
    has_many :usuarios, through: :listas
    validates :nombre, {presence: true,uniqueness: true,length: {minimum: 3, maximum: 50}}
    #validates :existencia, {presence: true}
    validates :categoria, {presence: true}
    #validates :asignado, {presence: true}
    
    def self.search(search)
      if search
        where('nombre LIKE ?', "%#{search}%")
      else
        all
      end
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :validate_user
  before_action :set_producto, only: [:show,:edit,:update,:destroy]

  #get /donadores
  def index
=begin 
    if(params[:query] != nil)
      require 'will_paginate/array'
      @productos = Producto.nombre(params[:query]).paginate(page: params[:page])
    else
      @productos = Producto.all.paginate(page: params[:page])
    end
=end
    #@productos = Producto.all
    @productos = Producto.paginate(page: params[:page])
    @listas = Lista.all
    @frutas = Producto.search(params[:search]).where(:categoria => "Frutas").order(:nombre)#.paginate(:page => params[:page], :per_page => 10)
    @verduras = Producto.search(params[:search]).where(:categoria => "Verduras").order(:nombre)#.paginate(:page => params[:page], :per_page => 10)
    @carnes = Producto.search(params[:search]).where(:categoria => "Carnes").order(:nombre)#.paginate(:page => params[:page], :per_page => 10)
    @abarrotes = Producto.search(params[:search]).where(:categoria => "Abarrotes").order(:nombre)#.paginate(:page => params[:page], :per_page => 10)
    @higiene = Producto.search(params[:search]).where(:categoria => "Higiene").order(:nombre)#.paginate(:page => params[:page], :per_page => 10)
    @granos = Producto.search(params[:search]).where(:categoria => "Granos/Semillas").order(:nombre)#.paginate(:page => params[:page], :per_page => 10)
    @congelados = Producto.search(params[:search]).where(:categoria => "Congelados").order(:nombre)#.paginate(:page => params[:page], :per_page => 10)
    @lacteos = Producto.search(params[:search]).where(:categoria => "Lacteos").order(:nombre)#.paginate(:page => params[:page], :per_page => 10)
  end
  
  def new
    @producto = Producto.new
  end
  
  #POST /productos
  def create
    @producto = Producto.new(producto_params)

   
    respond_to do |format|
        if @producto.save
           #flash[:notice] = 'Successfully created project.'
           #redirect_to donadores_path
          format.html { redirect_to productos_path, notice: 'Producto registrado' }
          format.json { render action: 'index', status: :created, location: @producto}
          # added:
          format.js   { render action: 'index', status: :created, location: @producto }
        else
            #render :new
          format.html { render action: 'new' }
          format.json { render json: @producto.errors, status: :unprocessable_entity }
          # added:
          format.js   { render json: @producto.errors, status: :unprocessable_entity }
        end
    end
  end

  #GET /donadores/:id
  def show
  
  end
  
  def edit
    set_producto
    #@producto = Producto.find(params[:id])
  end
  
  def update
    respond_to do |format|
      if set_producto.update_attributes(producto_params_edit)
        flash[:Exito] = "Datos del producto actualizados"
        format.html { redirect_to productos_path}
        format.json { render :index, status: :ok,location: @producto }
      else
        format.html {render :edit}
        format.json {render json: @producto.errors,status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @producto.destroy
    respond_to do | format |
      flash[:Exito] = "Producto eliminado"
      format.html {redirect_to productos_url}
      format.json {head :no_content}
    end
  end
  
  def activate
    set_producto
    #@producto = Producto.find(params[:id])
    if set_producto.update_attribute(:existencia, params[:data])
      #flash[:Exito] = "Usuario #{activo}"
    else
      
    end
     #redirect_to '/usuarios'
  end
  
  def desasignado
    #@productos = Producto.update_all(asignado: "No asignado")
    @productos = Producto.all
    respond_to do |format|
      if Lista.delete_all#@productos.update_all(asignado: "No asignado")
        flash[:Exito] = "Se han quitado las asignaciones"
        format.html { redirect_to productos_path}
        format.json { render :index, status: :ok,location: @producto }
      else
        flash[:Error] = "Error al remover las asignaciones"
        format.html {render :index}
        format.json {render json: @producto.errors,status: :unprocessable_entity }
      end
    end
  end
  
  def mi_lista_alimentos
    @padre = current_user
    @listas = Lista.where(usuario_id: @padre.idUsuario).paginate(:per_page => 20, :page => params[:page])
  end
  
  private
  
  def set_producto
    @producto = Producto.find(params[:id])
  end
  def producto_params
    params.require(:producto).permit(:nombre, :categoria,:existencia,:asignado)
  end
  
  def producto_params_edit
    params.require(:producto).permit(:nombre, :categoria,:asignado)
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_abarrotes.html.erb
<% @abarrotes.each do |producto| %>
    <%# if producto.categoria == "Abarrotes" %>
    <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.categoria %></td>
        <td>
        <div class="switch">
            <label>
                      No
                      <input id="Activo<%= producto.id %>" name="Activo" type="checkbox" 
                      onclick="productoActivo(<%= producto.id %>)" <%= if (producto.existencia) 
                                                                                  "checked" 
                                                                             end %>
                      >
                      <span class="lever"></span>
                      Si
            </label>
        </div>
        </td>
        <td>
            <% if producto.usuarios.count > 0 %>
                <% @listas.each do |lista|%> 
                    <% if lista.producto_id == producto.id%>
                        <%= lista.usuario.Nombre%> <%= lista.usuario.ApellidoPaterno%> <%= lista.usuario.ApellidoMaterno%><br>
                        <%#= producto.asignado %>
                    <%end%>
                <%end%>
            <%else%>
                <%= producto.asignado%>
            <%end%>
        </td>
        <td><a href="/productos/<%= producto.id%>/edit" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>
        <!--<td><a href="<%#= edit_producto_path(producto) %>" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>-->
        <% if producto.listas.count > 0 %>
          <td><a href="/productos" class="btn-floating btn modal-trigger red disabled" type="button"><i class="material-icons">delete</i></a></td>
        <% else %>
           <td><a href="/productos/<%= producto.id%>" class="btn-floating btn modal-trigger red" type="button" data-method="delete" data-confirm="<%= t('my.delete.product')%>"><i class="material-icons">delete</i></a></td>
        <% end %>
    </tr>
    <%# end %>
<% end %>

app/views/productos/_carnes.html.erb
<% @carnes.each do |producto| %>
    <%# if producto.categoria == "Carnes" %>
    <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.categoria %></td>
        <td>
        <div class="switch">
            <label>
              No
              <input id="Activo<%= producto.id %>" name="Activo" type="checkbox" 
              onclick="productoActivo(<%= producto.id %>)" <%= if (producto.existencia) 
                                                                          "checked" 
                                                                     end %>
              >
              <span class="lever"></span>
              Si
            </label>
        </div>
        </td>
        <td>
            <% if producto.usuarios.count > 0 %>
                <% @listas.each do |lista|%> 
                    <% if lista.producto_id == producto.id%>
                        <%= lista.usuario.Nombre%> <%= lista.usuario.ApellidoPaterno%> <%= lista.usuario.ApellidoMaterno%><br>
                        <%#= producto.asignado %>
                    <%end%>
                <%end%>
            <%else%>
                <%= producto.asignado%>
            <%end%>
        </td>
        <td><a href="/productos/<%= producto.id%>/edit" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>
        <!--<td><a href="<%#= edit_producto_path(producto) %>" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>-->
        <% if producto.listas.count > 0 %>
          <td><a href="/productos" class="btn-floating btn modal-trigger red disabled" type="button"><i class="material-icons">delete</i></a></td>
        <% else %>
           <td><a href="/productos/<%= producto.id%>" class="btn-floating btn modal-trigger red" type="button" data-method="delete" data-confirm="<%= t('my.delete.product')%>"><i class="material-icons">delete</i></a></td>
        <% end %>
    </tr>
    <%# end %>
<% end %>

app/views/productos/_congelados.html.erb
<% @congelados.each do |producto| %>
    <%# if producto.categoria == "Congelados" %>
    <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.categoria %></td>
        <td>
        <div class="switch">
            <label>
                      No
                      <input id="Activo<%= producto.id %>" name="Activo" type="checkbox" 
                      onclick="productoActivo(<%= producto.id %>)" <%= if (producto.existencia) 
                                                                                  "checked" 
                                                                             end %>
                      >
                      <span class="lever"></span>
                      Si
            </label>
        </div>
        </td>
        <td>
            <% if producto.usuarios.count > 0 %>
                <% @listas.each do |lista|%> 
                    <% if lista.producto_id == producto.id%>
                        <%= lista.usuario.Nombre%> <%= lista.usuario.ApellidoPaterno%> <%= lista.usuario.ApellidoMaterno%><br>
                        <%#= producto.asignado %>
                    <%end%>
                <%end%>
            <%else%>
                <%= producto.asignado%>
            <%end%>
        </td>
        <td><a href="/productos/<%= producto.id%>/edit" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>
        <!--<td><a href="<%#= edit_producto_path(producto) %>" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>-->
        <% if producto.listas.count > 0 %>
          <td><a href="/productos" class="btn-floating btn modal-trigger red disabled" type="button"><i class="material-icons">delete</i></a></td>
        <% else %>
           <td><a href="/productos/<%= producto.id%>" class="btn-floating btn modal-trigger red" type="button" data-method="delete" data-confirm="<%= t('my.delete.product')%>"><i class="material-icons">delete</i></a></td>
        <% end %>
    </tr>
    <%# end %>
<% end %>

app/views/productos/_form.html.erb
<%= form_for @producto, url: productos_path(@producto) do |p| %>
    <% @producto.errors.full_messages.each do |message| %>
    <div class="container">
          * <%= message %>
    </div>
    <% end %>
    <div class="row">
      <div class="input-field col s12 m6">
          <i class="material-icons prefix">shopping_cart</i>
          <%= p.label t('my.forms.same.name') %><br />
          <%= p.text_field :nombre, id: "nombre", type: "text", length: "100",class: "validate", required: 'true'%>
      </div>
    </div>
    <%= p.hidden_field :asignado, :value => "No asignado"%>
    <div class="row">
      <div class="input-field col s12 m6">
          <i class="material-icons prefix">view_module</i>
          <select name="producto[categoria]" id="categoria" required>
              <option value="" disabled selected><%= t('my.forms.same.select_product')%></option>
              <option value="Frutas">Frutas</option>
              <option value="Verduras">Verduras</option>
              <option value="Carnes">Carnes</option>
              <option value="Granos/Semillas">Granos/Semillas</option>
              <option value="Abarrotes">Abarrotes</option>
              <option value="Congelados">Congelados</option>
              <option value="Lacteos">Lacteos</option>
              <option value="Higiene">Higiene</option>
          </select>
      </div>
    </div>
    <%= p.hidden_field :existencia, :value => true%>
    <!--<div class="row">
       <div class="input-field col s12 m6">
          <i class="material-icons prefix">contacts</i>
          <%#=p.select :existencia, [['Si', true], ['No', false]]%>
      </div>
    </div>-->
    <br/><br/>
    <div class="row">
      <%= p.submit t('my.buttons.save'), :class => 'waves-effect waves-light btn' %>
      <%= link_to t('my.buttons.cancel').html_safe,'/productos',:class => 'btn waves-effect waves-light red'%>
    </div>
  <% end %>

app/views/productos/_frutas.html.erb
<% @frutas.each do |producto| %>
    <%# if producto.categoria == "Frutas" %>
    <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.categoria %></td>
        <td>
        <div class="switch">
            <label>
                      No
                      <input id="Activo<%= producto.id %>" name="Activo" type="checkbox" 
                      onclick="productoActivo(<%= producto.id %>)" <%= if (producto.existencia) 
                                                                                  "checked" 
                                                                             end %>
                      >
                      <span class="lever"></span>
                      Si
            </label>
        </div>
        </td>
        <td>
        <% if producto.usuarios.count > 0 %>
            <% @listas.each do |lista|%> 
                <% if lista.producto_id == producto.id%>
                    <%= lista.usuario.Nombre%> <%= lista.usuario.ApellidoPaterno%> <%= lista.usuario.ApellidoMaterno%><br>
                    <%#= producto.asignado %>
                <%end%>
            <%end%>
        <%else%>
            <%= producto.asignado%>
        <%end%>
        </td>
        <td><a href="/productos/<%= producto.id%>/edit" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>
        <!--<td><a href="<%#= edit_producto_path(producto) %>" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>-->
        <% if producto.listas.count > 0 %>
          <td><a href="/productos" class="btn-floating btn modal-trigger red disabled" type="button"><i class="material-icons">delete</i></a></td>
        <% else %>
           <td><a href="/productos/<%= producto.id%>" class="btn-floating btn modal-trigger red" type="button" data-method="delete" data-confirm="<%= t('my.delete.product')%>"><i class="material-icons">delete</i></a></td>
        <% end %>
    </tr>
    <%# end %>
<% end %>

app/views/productos/_higiene.html.erb
<% @higiene.each do |producto| %>
    <%# if producto.categoria == "Higiene" %>
    <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.categoria %></td>
        <td>
        <div class="switch">
            <label>
                      No
                      <input id="Activo<%= producto.id %>" name="Activo" type="checkbox" 
                      onclick="productoActivo(<%= producto.id %>)" <%= if (producto.existencia) 
                                                                                  "checked" 
                                                                             end %>
                      >
                      <span class="lever"></span>
                      Si
            </label>
        </div>
        </td>
        <td>
            <% if producto.usuarios.count > 0 %>
                <% @listas.each do |lista|%> 
                    <% if lista.producto_id == producto.id%>
                        <%= lista.usuario.Nombre%> <%= lista.usuario.ApellidoPaterno%> <%= lista.usuario.ApellidoMaterno%><br>
                        <%#= producto.asignado %>
                    <%end%>
                <%end%>
            <%else%>
                <%= producto.asignado%>
            <%end%>
        </td>
        <td><a href="/productos/<%= producto.id%>/edit" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>
        <!--<td><a href="<%#= edit_producto_path(producto) %>" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>-->
        <% if producto.listas.count > 0 %>
          <td><a href="/productos" class="btn-floating btn modal-trigger red disabled" type="button"><i class="material-icons">delete</i></a></td>
        <% else %>
           <td><a href="/productos/<%= producto.id%>" class="btn-floating btn modal-trigger red" type="button" data-method="delete" data-confirm="<%= t('my.delete.product')%>"><i class="material-icons">delete</i></a></td>
        <% end %>
    </tr>
    <%# end %>
<% end %>

app/views/productos/_lacteos.html.erb
<% @lacteos.each do |producto| %>
    <%# if producto.categoria == "Lacteos" %>
    <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.categoria %></td>
        <td>
        <div class="switch">
            <label>
                      No
                      <input id="Activo<%= producto.id %>" name="Activo" type="checkbox" 
                      onclick="productoActivo(<%= producto.id %>)" <%= if (producto.existencia) 
                                                                                  "checked" 
                                                                             end %>
                      >
                      <span class="lever"></span>
                      Si
            </label>
        </div>
        </td>
        <td>
            <% if producto.usuarios.count > 0 %>
                <% @listas.each do |lista|%> 
                    <% if lista.producto_id == producto.id%>
                        <%= lista.usuario.Nombre%> <%= lista.usuario.ApellidoPaterno%> <%= lista.usuario.ApellidoMaterno%><br>
                        <%#= producto.asignado %>
                    <%end%>
                <%end%>
            <%else%>
                <%= producto.asignado%>
            <%end%>
        </td>
        <td><a href="/productos/<%= producto.id%>/edit" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>
        <!--<td><a href="<%#= edit_producto_path(producto) %>" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>-->
        <% if producto.listas.count > 0 %>
          <td><a href="/productos" class="btn-floating btn modal-trigger red disabled" type="button"><i class="material-icons">delete</i></a></td>
        <% else %>
           <td><a href="/productos/<%= producto.id%>" class="btn-floating btn modal-trigger red" type="button" data-method="delete" data-confirm="<%= t('my.delete.product')%>"><i class="material-icons">delete</i></a></td>
        <% end %>
    </tr>
    <%# end %>
<% end %>

app/views/productos/_semillas.html.erb
<% @granos.each do |producto| %>
    <%# if producto.categoria == "Granos/Semillas" %>
    <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.categoria %></td>
        <td>
        <div class="switch">
            <label>
                      No
                      <input id="Activo<%= producto.id %>" name="Activo" type="checkbox" 
                      onclick="productoActivo(<%= producto.id %>)" <%= if (producto.existencia) 
                                                                                  "checked" 
                                                                             end %>
                      >
                      <span class="lever"></span>
                      Si
            </label>
        </div>
        </td>
        <td>
            <% if producto.usuarios.count > 0 %>
                <% @listas.each do |lista|%> 
                    <% if lista.producto_id == producto.id%>
                        <%= lista.usuario.Nombre%> <%= lista.usuario.ApellidoPaterno%> <%= lista.usuario.ApellidoMaterno%><br>
                        <%#= producto.asignado %>
                    <%end%>
                <%end%>
            <%else%>
                <%= producto.asignado%>
            <%end%>
        </td>
        <td><a href="/productos/<%= producto.id%>/edit" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>
        <!--<td><a href="<%#= edit_producto_path(producto) %>" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>-->
        <% if producto.listas.count > 0 %>
          <td><a href="/productos" class="btn-floating btn modal-trigger red disabled" type="button"><i class="material-icons">delete</i></a></td>
        <% else %>
           <td><a href="/productos/<%= producto.id%>" class="btn-floating btn modal-trigger red" type="button" data-method="delete" data-confirm="<%= t('my.delete.product')%>"><i class="material-icons">delete</i></a></td>
        <% end %>
    </tr>
    <%# end %>
<% end %>

app/views/productos/_verduras.html.erb
<% @verduras.each do |producto| %>
    <%# if producto.categoria == "Verduras" %>
    <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.categoria %></td>
        <td>
        <div class="switch">
            <label>
                      No
                      <input id="Activo<%= producto.id %>" name="Activo" type="checkbox" 
                      onclick="productoActivo(<%= producto.id %>)" <%= if (producto.existencia) 
                                                                                  "checked" 
                                                                             end %>
                      >
                      <span class="lever"></span>
                      Si
            </label>
        </div>
        </td>
        <td>
            <% if producto.usuarios.count > 0 %>
                <% @listas.each do |lista|%> 
                    <% if lista.producto_id == producto.id%>
                        <%= lista.usuario.Nombre%> <%= lista.usuario.ApellidoPaterno%> <%= lista.usuario.ApellidoMaterno%><br>
                        <%#= producto.asignado %>
                    <%end%>
                <%end%>
            <%else%>
                <%= producto.asignado%>
            <%end%>
        </td>
        <td><a href="/productos/<%= producto.id%>/edit" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>
        <!--<td><a href="<%#= edit_producto_path(producto) %>" class="btn-floating btn " type="button"><i class="tiny material-icons">mode_edit</i></a></td>-->
        <% if producto.listas.count > 0 %>
          <td><a href="/productos" class="btn-floating btn modal-trigger red disabled" type="button"><i class="material-icons">delete</i></a></td>
        <% else %>
           <td><a href="/productos/<%= producto.id%>" class="btn-floating btn modal-trigger red" type="button" data-method="delete" data-confirm="<%= t('my.delete.product')%>"><i class="material-icons">delete</i></a></td>
        <% end %>
    </tr>
    <%# end %>
<% end %>

app/views/productos/edit.html.erb
<h4><%= t('my.buttons.edit')%> <%= @producto.nombre %></h4>

<div class="divider"></div><br/>

<%#= form_for(@producto) do |p| %>
<%= form_for @producto,:url => {:controller => "productos", :action => "update" } do |p| %>
  <% @producto.errors.full_messages.each do |message| %>
    <div class="container">
      *<%= message%>
    </div>
  <% end %>
  <div class="row">
    <div class="input-field col s12 m6">
      <i class="material-icons prefix">shopping_cart</i>
      <%= p.label t('my.forms.same.name') %><br />
      <%= p.text_field :nombre, id: "nombre", type: "text", length: "100",class: "validate", required: 'true'%>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12 m6">
      <i class="material-icons prefix">view_module</i>
      <select name="producto[categoria]" id="categoria" required>
        <option value="<%= @producto.categoria %>" selected><%= @producto.categoria %></option>
        <option value="Frutas">Frutas</option>
        <option value="Verduras">Verduras</option>
        <option value="Carnes">Carnes</option>
        <option value="Granos/Semillas">Granos/Semillas</option>
        <option value="Abarrotes">Abarrotes</option>
        <option value="Congelados">Congelados</option>
        <option value="Lacteos">Lacteos</option>
        <option value="Higiene">Higiene</option>
      </select>
    </div>
  </div>
  <%= p.hidden_field :asignado, :value => "No asignado" %>
  <br/><br/>
  <div class="row">
    <%= p.submit t('my.buttons.save'), :class => 'waves-effect waves-light btn' %>
    <%= link_to t('my.buttons.cancel').html_safe,'/productos',:class => 'btn waves-effect waves-light red'%>
  </div>
<% end %>